
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mini_project"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb"
  app-jwt-expiration-milliseconds: 604800000 #in seconds

