
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mini_project"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "clA8K37zrOY5EoPGI0TLUCJZmCik3ZBpgju5SZHny3nR/TcZYRz4lh3FIkLec2lZ"
  app-jwt-expiration-milliseconds: 604800000 #in seconds

